#Include DEBUG file structure on the build tree
CONTIKI_SOURCEFILES += serial-debug.c
CONTIKI_SOURCEDIRS += .

ifeq ($(CONTIKI_WITH_SERIAL_DEBUG), 1)
  CFLAGS += -DWITH_SERIAL_DEBUG=1
else
  CFLAGS += -DWITH_SERIAL_DEBUG=0
endif

